/*
 * cardreader.c
 *
 *  Created on: 2015-02-03
 *      Author: Daniel
 */

#include "cardreader.h"

alt_up_audio_dev *audio;
alt_up_sd_card_dev *sd_card = NULL;

short int file_handle;
long file_size;
unsigned int *audio_stream;
volatile long stream_position;

void av_config_setup(){
	printf("Configuring audio and video.\n");
	alt_up_av_config_dev * av_config = alt_up_av_config_open_dev("/dev/audio_and_video_config_0");
	while (!alt_up_av_config_read_ready(av_config));
	audio = alt_up_audio_open_dev("/dev/audio_0");
	alt_up_audio_reset_audio_core(audio);
}

void audio_ISR_once() {
	alt_up_audio_write_fifo(audio, &audio_stream[stream_position], BUFFER_SIZE, ALT_UP_AUDIO_LEFT);
	alt_up_audio_write_fifo(audio, &audio_stream[stream_position], BUFFER_SIZE, ALT_UP_AUDIO_RIGHT);
	stream_position += BUFFER_SIZE;
	if (stream_position >= file_size - BUFFER_SIZE) {
		alt_up_audio_disable_write_interrupt(audio);
		alt_up_audio_disable_write_interrupt(audio);
		alt_up_audio_disable_write_interrupt(audio);
	}
}
void audio_ISR_repeat() {
	alt_up_audio_write_fifo(audio, &audio_stream[stream_position], BUFFER_SIZE, ALT_UP_AUDIO_LEFT);
	alt_up_audio_write_fifo(audio, &audio_stream[stream_position], BUFFER_SIZE, ALT_UP_AUDIO_RIGHT);
	stream_position += BUFFER_SIZE;
	if (stream_position >= file_size - BUFFER_SIZE) {
		stream_position = 0;
	}
}

char openFileinSD(char* fileName, short int* file_handle_ptr){
	short int file_handle;
	char status = -1;

	sd_card = alt_up_sd_card_open_dev("/dev/SD_Card");

	if (sd_card != NULL){
		while(1){
			if (alt_up_sd_card_is_Present()){
				printf("Card Found.\n");
				if (alt_up_sd_card_is_FAT16()){
					printf("FAT16.\n");
					file_handle = alt_up_sd_card_fopen( fileName, false );
					if ( file_handle == -1 )
						printf( "*** File cannot be opened.\n");
					else if ( file_handle == -2 )
						printf( "*** File already opeend.\n");
					else {
						*file_handle_ptr = file_handle;
						status = 0;
						printf( "File obtained.\n");
						return status;
					}
					printf("*** Error reading File.\n");
				} else {
					printf("*** NOT FAT16.\n");
				}
			}
		}
	}
	printf("*** Storage Device may not found.\n");
	return status;
}

int setBackground(char* file_name){

	unsigned int pixel_buffer_addr1 = PIXEL_BUFFER_BASE; // base address of SRAM, generated by Qsys
	unsigned int pixel_buffer_addr2 = PIXEL_BUFFER_BASE + (512 * 240 * 2);
	unsigned int R,RED=0;
	unsigned int G,GREEN=0;
	unsigned int B,BLUE=0;
	unsigned int *DATA;
	unsigned int add = 0;
	int x,y;
	int j=76799;
	int data_stream=0;

	//initialize
	alt_up_pixel_buffer_dma_dev* pixel_buffer;
	pixel_buffer = alt_up_pixel_buffer_dma_open_dev("/dev/pixel_buffer_dma");
	alt_up_pixel_buffer_dma_change_back_buffer_address(pixel_buffer, pixel_buffer_addr1);
	alt_up_pixel_buffer_dma_swap_buffers(pixel_buffer);
	while (alt_up_pixel_buffer_dma_check_swap_buffers_status(pixel_buffer));
	alt_up_pixel_buffer_dma_change_back_buffer_address(pixel_buffer, pixel_buffer_addr2);

	//blackclear
	alt_up_pixel_buffer_dma_clear_screen(pixel_buffer, 0);
	alt_up_pixel_buffer_dma_clear_screen(pixel_buffer, 1);

	if (openFileinSD(file_name, &file_handle) == 0){

		//parse
		for (data_stream = 0; data_stream < 76999; data_stream++){
			if( data_stream <= 199 ){
				alt_up_sd_card_read(file_handle);
				alt_up_sd_card_read(file_handle);
				alt_up_sd_card_read(file_handle);
			}else {
				RED = alt_up_sd_card_read(file_handle); R = (RED   >> 3) & 0x001f;
				GREEN = alt_up_sd_card_read(file_handle); G = ( (GREEN >> 2) & 0x003f ) << 5;
				BLUE = alt_up_sd_card_read(file_handle); B = ( (BLUE  >> 3) & 0x001f ) << 11;
				DATA[data_stream-18] = (unsigned short int) (R | G | B);
			}
		} alt_up_sd_card_fclose(file_handle);

		//write
		for (y=0;y<240;y++){
			add = ((y & pixel_buffer->y_coord_mask) << pixel_buffer->y_coord_offset);
			for(x=319;x>=0;x--){
				IOWR_16DIRECT(pixel_buffer->buffer_start_address, add+2*x, DATA[j]);
				j--;
			}
		}
		return 0;
	}
	return -1;
}

int load_song(char* file_name){
	file_size = 0;

	if (openFileinSD(file_name, &file_handle) == 0){
		char a;
		char b;
		char *data_str = "data";
		int i, j;

		for (i = 0; i < 45; i++) {
			a = (char) alt_up_sd_card_read(file_handle);
			printf("%c\n", a);
			if (a == data_str[j]) {
				j++;
				if (j == 3) {
					alt_up_sd_card_read(file_handle); // letter A
					char byte_0 = (char) alt_up_sd_card_read(file_handle);
					char byte_1 = (char) alt_up_sd_card_read(file_handle);
					char byte_2 = (char) alt_up_sd_card_read(file_handle);
					char byte_3 = (char) alt_up_sd_card_read(file_handle);
					file_size = ((unsigned char) byte_3 << 24)
							| ((unsigned char) byte_2 << 16)
							| ((unsigned char) byte_1 << 8)
							| (unsigned char) byte_0;
					printf("Music file size: %lu\n", file_size);
				}
			} else {
				j = 0;
				printf("we are in else\n");
			}
		}

		unsigned int WHY[file_size];
		audio_stream = WHY;
		if (audio_stream == NULL) {
			printf("*** Failed to allocate left audio stream!");
			exit(1);
		}

		short converter;
		while (file_size < file_size / 2) {
			b = (char) alt_up_sd_card_read(file_handle);
			a = (char) alt_up_sd_card_read(file_handle);
			converter = ((unsigned char) a << 8) | (unsigned char) b;
			converter = converter/2;
			audio_stream[file_size] = converter;
			file_size++;
		}

	}
	else
		printf("*** Error Loading Song.\n");
	return 3;
}

void play_songO(){
	printf("Starting music. \n");
	printf("Song Size: %lu, byte: 0x%08x\n", file_size, audio_stream[file_size - 41]);

	alt_irq_register(AUDIO_0_IRQ, 0, audio_ISR_once);
	alt_up_audio_enable_write_interrupt(audio);
}

void play_songR(){
	printf("Starting music. \n");
	printf("Song Size: %lu, byte: 0x%08x\n", file_size, audio_stream[file_size - 41]);

	alt_irq_register(AUDIO_0_IRQ, 0, audio_ISR_repeat);
	alt_up_audio_enable_write_interrupt(audio);
}
